services:
  mariadb:
    container_name: db
    image: lscr.io/linuxserver/mariadb
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=EST
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DB_DBNAME}
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes: 
          - ./mariadbData:/var/lib/mysql/
    ports:
        - "3307:3306"
  calrouter:
    container_name: cal_router
    build:
      context: .
      target: router
    command: "/app/router/server"
    ports:
      - "8080:8080"
    env_file: .env
  calorietracker:
    build: .
networks:
  default:
    name: N_calorieTracker